# Lengthen uptime output
long_uptime = true

# Lengthen kernel output
long_kernel = false

# Lengthen shell output
long_shell = false

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Specify the theme to use
theme = "fabse"