icon: &icon
  font: 'RobotoMono Nerd Font:pixelsize=14'

bar:
  location: top
  height: 15
  font: RobotoMono Nerd Font:size=12
  background: 080808FF
  spacing: 10

  left:
    - foreign-toplevel:
        content:
          map:
            tag: activated
            values:
              false: {empty: {}}
              true:
                - string: {text: "{app-id}: {title}"}
    - script:
        path: /home/fabse/.config/yambar/playerctl/playerctl
        content:
          - map:
              tag: playing
              values:
                true:
                  - string: {text: "\uF04B {title} ", foreground: "5FFF47FF"}
                false:
                  - string: {text: "\uF04C {title} ", foreground: "FFD78740"}
  right:
    - river:
         title: {string: { text: "{seat} - {title}" }}
         content:
          map:
            tag: occupied
            values:
              false: {empty: {}}
              true:
                string:
                  margin: 5
                  text: "{id}: {state}"
    - script:
        path: /home/fabse/.config/yambar/weather.sh
        foreground: 'FFD787FF'
        content:
          - string: {text: "{icon}", font: "owfont", <<: *icon}
          - string: {text: " {temp}\u00B0"}
          - string: {text: " ({feels_like}\u00B0)"}
    - script:
        path: /home/fabse/.config/yambar/pulse/pulse
        foreground: 'AF87FFFF'
        content:
          - map:
              tag: headset
              values:
                true:
                  - string: {text: "\uF7CA", <<: *icon}
                false:
                  - string: {text: "\uF886", <<: *icon}
          - string: {text: " {volume}%"}
    - script:
        path: /home/fabse/.config/yambar/cpu.sh
        foreground: '5FD7FFFF'
        content:
          map:
            tag: high
            values:
              true:
                - string: {text: "{bar}", foreground: 'FF206FFF'}
                - string: {text: " {value}%", foreground: 'FF206FFF'}
              false:
                - string: {text: "{bar}"}
                - string: {text: " {value}%"}
    - backlight:
        name: intel_backlight
        content:
          string: {text: "backlight: {percent}%"}
    - mem:
        interval: 2500
        content:
          string: {text: "memory: {percent_used}%"}
    - network:
        name: 'wlan0'
        content:
          map:
            tag: carrier
            values:
              true:
                map:
                  tag: state
                  default:
                    string: {text: "\uF6D7   {ssid}"}
                  values:
                    up:
                      string: {text: "\uFAA8   {ssid}"}
                    false:
                      string: {text: "\uF818   offline"}
    - clock:
        foreground: FFD787FF
        time-format: "%d %b, %H:%M"
        content:
          - string: {text: "{time}"}
    - battery:
        name: BAT1
        poll-interval: 5
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: ' ', foreground: ff0000ff}
                      - string: {text: ' ', foreground: ffa600ff}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ',}
                      - string: {text: ' ', foreground: 00ff00ff}
                - string: {text: "   {capacity}%"}
        content:
          map:
            tag: state
            values:
              unknown:
                <<: *discharging
              discharging:
                <<: *discharging
              charging: &charging
                - string: {text: ' ', foreground: 00ff00ff}
                - string: {text: " {capacity}%"}
              full:
                - string: {text: ' ', foreground: 00ff00ff}
                - string: {text: " {capacity}%"}
              not charging:
                 - ramp:
                     tag: capacity
                     items:
                       - string: {text: '  ', foreground: ff0000ff}
                       - string: {text: '  ', foreground: ffa600ff}
                       - string: {text: '  ', foreground: 00ff00ff}
                       - string: {text: '  ', foreground: 00ff00ff}
                       - string: {text: '  ', foreground: 00ff00ff}
                       - string: {text: '  ', foreground: 00ff00ff}
                       - string: {text: '  ', foreground: 00ff00ff}
                       - string: {text: '  ', foreground: 00ff00ff}
                       - string: {text: '  ', foreground: 00ff00ff}
                       - string: {text: '  ', foreground: 00ff00ff}
                 - string: {text: "   {capacity}%"}
