[theme]
theme = "solarized-dark"
[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $prev $play $next |}"
interface_name_exclude = [".*kdeconnect.*", "mpd"]

[[block]]
block = "pacman"
interval = 86640
format = " $icon $pacman + $aur = $both updates "
format_singular = " $icon $both update available "
format_up_to_date = " $icon system up to date "
aur_command = "paru -Qua"
signal = 1

[[block]]
block = "sound"
step_width = 2
[block.mappings]
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"

[[block]]
block = "hueshift"
hue_shifter = "wl_gammarelay_rs"
step = 100
click_temp = 3000

[[block]]
block = "backlight"
device = "amdgpu_bl1"
minimum = 0
maximum = 100
step_width=2

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_used.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "amd_gpu"
device = "card1"
format = " $icon $utilization "
format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
interval = 2

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization $frequency "
format_alt = " $icon $barchart $utilization $frequency "

[[block]]
block = "temperature"
format = " $icon $average average "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "zenpower-pci-00c3"

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "time"
interval = 1
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m %T') "
short = " $icon $timestamp.datetime(f:%R) "
