#!/bin/sh

# Services to execute at start
/usr/bin/dunst
/usr/bin/pipewire
/usr/bin/pipewire-pulse
/usr/bin/wireplumber
/usr/bin/syncthing
bash /home/fabse/scripts/sunpaper.sh -d
foot --server

# Set mod-key
mod="Mod4"

# Shortcut to terminal
riverctl map normal $mod Return spawn 'footclient' &

# dmenu replacement with the gruvbox material color, of course
riverctl map normal mod spawn "dmenu_run_gruv" &

# Volume control
riverctl map normal None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +2%'
riverctl map normal None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -2%'
riverctl map normal None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

# Audio player control
riverctl map normal None XF86AudioMedia spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPlay  spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev  spawn 'playerctl previous'
riverctl map normal None XF86AudioNext  spawn 'playerctl next'

# Brightness control
riverctl map normal None XF86MonBrightnessUp   spawn 'brightnessctl set +2%'
riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl set 2%-'

# Take screenshot with wayshot + swappy
riverctl map normal Print spawn 'wayshot --stdout | swappy -f -'

# mod+Q to close the focused view
riverctl map normal modQ close &

# mod+Shift+E to exit river
riverctl map normal mod+Shift E exit &

# mod+J and mod+K to focus the next/previous view in the layout stack
riverctl map normal modJ focus-view next &
riverctl map normal modK focus-view previous &

# mod+Shift+J and mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal mod+Shift J swap next &
riverctl map normal mod+Shift K swap previous &

# mod+Period and mod+Comma to focus the next/previous output
riverctl map normal modPeriod focus-output next &
riverctl map normal modComma focus-output previous &

# mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal mod+Shift Period send-to-output next &
riverctl map normal mod+Shift Comma send-to-output previous &

# mod+H and mod+L to decrease/increase the main ratio of rivercarro(1)
riverctl map normal modH send-layout-cmd rivercarro "main-ratio -0.05" &
riverctl map normal modL send-layout-cmd rivercarro "main-ratio +0.05" &

# mod+Shift+H and mod+Shift+L to increment/decrement the main count of rivercarro(1)
riverctl map normal mod+Shift H send-layout-cmd rivercarro "main-count +1" &
riverctl map normal mod+Shift L send-layout-cmd rivercarro "main-count -1" &

# mod+Alt+{H,J,K,L} to move views
riverctl map normal mod+Alt H move left 100 &
riverctl map normal mod+Alt J move down 100 &
riverctl map normal mod+Alt K move up 100 &
riverctl map normal mod+Alt L move right 100 &

# mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal mod+Alt+Control H snap left &
riverctl map normal mod+Alt+Control J snap down &
riverctl map normal mod+Alt+Control K snap up &
riverctl map normal mod+Alt+Control L snap right &

# mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal mod+Alt+Shift H resize horizontal -100 &
riverctl map normal mod+Alt+Shift J resize vertical 100 &
riverctl map normal mod+Alt+Shift K resize vertical -100 &
riverctl map normal mod+Alt+Shift L resize horizontal 100 &

# mod+ Left Mouse Button to move views
riverctl map-pointer normal modBTN_LEFT move-view &

# mod+ Right Mouse Button to resize views
riverctl map-pointer normal modBTN_RIGHT resize-view &

for i in $(seq 1 5)
do
    tags=$((1 << ($i - 1)))

    # mod+[1-9] to focus tag [0-8]
    riverctl map normal mod$i set-focused-tags $tags &

    # mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal mod+Shift $i set-view-tags $tags &

    # mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal mod+Control $i toggle-focused-tags $tags &

    # mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal mod+Shift+Control $i toggle-view-tags $tags &
done

# mod+0 to focus all tags
# mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal mod0 set-focused-tags $all_tags &
riverctl map normal mod+Shift 0 set-view-tags $all_tags &

riverctl map normal modS focus-previous-tags &

# mod+Space to toggle float
riverctl map normal modR toggle-float &

# mod+F to toggle fullscreen
riverctl map normal modF toggle-fullscreen &

# mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal modUp    send-layout-cmd rivercarro "main-location top" &
riverctl map normal modRight send-layout-cmd rivercarro "main-location right" &
riverctl map normal modown  send-layout-cmd rivercarro "main-location bottom" &
riverctl map normal modLeft  send-layout-cmd rivercarro "main-location left" &

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough &

# mod+F11 to enter passthrough mode
riverctl map normal modF11 enter-mode passthrough &

# mod+F11 to return to normal mode
riverctl map passthrough modF11 enter-mode normal &

# Set background and border color
riverctl border-color-unfocused 0x525252 &
riverctl border-color-focused 0xBE6C38 &
riverctl border-width 3 &

riverctl focus-follows-cursor normal &

# Set keyboard repeat rate
riverctl set-repeat 50 300 &

# Make certain views start floating
riverctl float-filter-add app-id float &
riverctl float-filter-add title "popup title with spaces" &
riverctl float-filter-add app-id "Gpick" &

riverctl xcursor-theme "Bibata-Rainbow-Modern" 32 &

gsettings set "$gnome_schema" gtk-theme "Sweet-Dark"
gsettings set "$gnome_schema" icon-theme "Tela-blue"
gsettings set "$gnome_schema" cursor-theme "Bibata-Rainbow-Modern"

# Set and exec into the default layout generator, rivercarro.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
exec rivercarro -inner-gaps 3 -outer-gaps 3 -main-ratio 0.5
