#!/bin/bash

# Run dbus-session
  riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river XDG_SESSION_DESKTOP=river" &

# Set default wallpaper
  riverctl spawn "swaybg -m fill -i /home/fabse/wallpapers/natsu-and-happy.jpg" &

# Set default terminal depending on foot running or not
  if ! [[ $(pidof foot) ]]; then
    terminal="footclient"
  elif [[ $(pidof foot) ]]; then
    if ! [[ $(pidof sway) ]]; then
      terminal="footclient"
    else
      terminal="foot"
    fi
  fi

# Services to execute at start
  bash /home/fabse/scripts/autostart.sh river &

# Shortcut to terminal
  riverctl map normal Super Return spawn $terminal &

# Shortcut to launcher
  riverctl map normal Super D spawn wofi &

# Shortcut to take screenshot with wayshot + swappy
  riverctl map normal None Print spawn "wayshot --stdout | swappy -f -"

# Shortcut to toggle night mode
  riverctl map normal Super y spawn "wlsunset -l 14.6 -L 121" &

# Theme and mouse-cursor
  riverctl xcursor-theme Bibata-Rainbow-Modern 32 &
  riverctl focus-follows-cursor normal &
  gnome_schema="org.gnome.desktop.interface" &
  gsettings set $gnome_schema gtk-theme "Sweet-Dark" &
  gsettings set $gnome_schema icon-theme "Tela-blue" &
  gsettings set $gnome_schema cursor-theme "Bibata-Rainbow-Modern" &
  gsettings set $gnome_schema cursor-size "32" &

# Audio and brightness controls
  for mode in normal locked; do
    riverctl map $mode None XF86AudioRaiseVolume  spawn "pactl set-sink-volume @DEFAULT_SINK@ +2%"
    riverctl map $mode None XF86AudioLowerVolume  spawn "pactl set-sink-volume @DEFAULT_SINK@ -2%"
    riverctl map $mode None XF86AudioMute         spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"

    riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPlay  spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev  spawn "playerctl previous"
    riverctl map $mode None XF86AudioNext  spawn "playerctl next"

    riverctl map $mode None XF86MonBrightnessUp   spawn "brightnessctl set +2%"
    riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl set 2%-"
  done

# Shortcut to screenlock
  riverctl map normal Control l spawn "swaylock -f"

# Shortcut to exit river
  riverctl map normal Super+Shift E spawn "/home/fabse/scripts/logout.sh river"

# Shortcut to reload river configuration
  riverctl map normal Super+Shift C spawn "~/.config/river/init"

# Shortcut to toggle float
  riverctl map normal Super Space toggle-float

# Shortcut to toggle fullscreen
  riverctl map normal Super+Shift F toggle-fullscreen

# Shortcut to close the focused view
  riverctl map normal Super Q close

# Shortcut to focus the next/previous view in the layout stack
  riverctl map normal Super N focus-view next
  riverctl map normal Super P focus-view previous

# Shortcut to swap the focused view with the next/previous view in the layout stack
  riverctl map normal Super+Shift N swap next
  riverctl map normal Super+Shift P swap previous

# Shortcut to focus the next/previous output
  riverctl map normal Super Period focus-output next
  riverctl map normal Super Comma focus-output previous

# Shortcut to send the focused view to the next/previous output
  riverctl map normal Super+Shift+Period send-to-output next
  riverctl map normal Super+Shift+Comma send-to-output previous

# Shortcut to decrease/increase the main ratio of rivercarro(1)
  riverctl map normal Super H send-layout-cmd rivercarro "main-ratio -0.05"
  riverctl map normal Super L send-layout-cmd rivercarro "main-ratio +0.05"

# Shortcut to increment/decrement the main count of rivercarro(1)
  riverctl map normal Super+Shift H send-layout-cmd rivercarro "main-count +1"
  riverctl map normal Super+Shift L send-layout-cmd rivercarro "main-count -1"

# Shortcut to move views
  riverctl map normal Super+Alt L move left 100
  riverctl map normal Super+Alt D move down 100
  riverctl map normal Super+Alt U move up 100
  riverctl map normal Super+Alt R move right 100

# Shortcut to snap views to screen edges
  riverctl map normal Super+Alt+Control L snap left
  riverctl map normal Super+Alt+Control D snap down
  riverctl map normal Super+Alt+Control U snap up
  riverctl map normal Super+Alt+Control R snap right

# Shortcut to resize views
  riverctl map normal Super+Alt+Shift L resize horizontal -100
  riverctl map normal Super+Alt+Shift D resize vertical 100
  riverctl map normal Super+Alt+Shift U resize vertical -100
  riverctl map normal Super+Alt+Shift R resize horizontal 100

# Shortcut to move views
  riverctl map-pointer normal Super BTN_LEFT move-view

# Shortcut to resize views
  riverctl map-pointer normal Super BTN_RIGHT resize-view

  for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))

    # Shortcut to focus tag [0-8]
      riverctl map normal Super $i set-focused-tags $tags

    # Shortcut to tag focused view with tag [0-8]
      riverctl map normal Super+Shift $i set-view-tags $tags

    # Shortcut to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Shortcut to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
  done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
  all_tags=$(((1 << 32) - 1))

  riverctl map normal Super 0 set-focused-tags $all_tags
  riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Shortcut to change layout orientation
  riverctl map normal Super Up    send-layout-cmd rivercarro "main-location top"
  riverctl map normal Super Right send-layout-cmd rivercarro "main-location right"
  riverctl map normal Super Down  send-layout-cmd rivercarro "main-location bottom"
  riverctl map normal Super Left  send-layout-cmd rivercarro "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
  riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
  riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
  riverctl map passthrough Super F11 enter-mode normal

# Set background and border color
  riverctl background-color 0x002b36
  riverctl border-color-focused 0x93a1a1
  riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
  riverctl set-repeat 50 300

# Make certain views start floating
  riverctl float-filter-add app-id float
  riverctl float-filter-add app-id fabse_launcher
  riverctl float-filter-add "popup"
  riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
  riverctl csd-filter-remove app-id "firefox"
  riverctl csd-filter-remove app-id "zathura"

# Touchpad-configs
  for pad in $(riverctl list-inputs | grep -i touchpad ); do
    riverctl input $pad events enabled
    riverctl input $pad tap enabled
  done

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
  riverctl default-layout rivercarro
  exec rivercarro -inner-gaps 3 -outer-gaps 3 -main-ratio 0.55
