theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "sound"
format = "{output_name} {volume}"
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "🎧"

[[block]]
block = "hueshift"
hue_shifter = "wlsunset"
step = 100
click_temp = 3000

[[block]]
block = "backlight"
device = "intel_backlight"
step_width=2

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min} min, {max} max, {average} avg"
chip = "*-isa-*"
inputs = ["Package id 0"]

[[block]]
block = "battery"
driver = "upower"
device="BAT1"
format = "{percentage:6#100} {percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
