fallback = ''
separator = ' '

[matching]
'discord' = ''
'WebCord' = ''
'Element' = ''
'Signal' = ''
'balena-etcher' = ''
'Steam' = ''
'lutris' = ''
'visualboyadvance-m' = ''
'vlc' = ''
"com.obsproject.Studio" = ''
'Gimp-2.10' = ''
"vimiv" = ''
'pavucontrol' = ''
'org.gnome.Nautilus' = ''
'nemo' = ''
'eog' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'betterbird' = ''
'Bitwarden' = ''
'Brave' = ''
'mousepad' = ''
'Code' = ''
'code-oss' = ''
'Emacs' = ''
'org.gnome.Calculator' = ''
"transmission-remote-gtk" = ""
'Spotify' = ''
'deezer-enhanced' = ''
'nuclear' = ''
'/(?i)^Github.*Firefox/' = ''
'firefox' = ''
'LibreWolf' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
'foot' = ''
'footclient' = ''
'virt-manager' = ''
"org.freecad.FreeCAD"= ""
"com/.https://ultimaker.UltiMaker-Cura"= ""
"remarkhub" = ""
"org.pwmt.zathura" = ''