services:
  archivebox:
    image: archivebox/archivebox:dev
    container_name: ArchiveBox
    command: server --quick-init 0.0.0.0:12346 schedule --foreground --every=day --depth=1 'https://getpocket.com/users/fabseman/feed/all'
    ports:
      - 12346:8000
    environment:
      - ALLOWED_HOSTS=*                   # add any config options you want as env vars
      - MEDIA_MAX_SIZE=750m
      - USE_COLOR=True
      - SHOW_PROGRESS=False
    volumes:
      - /media/SEAGATe/FABSE_GATE/Diverse/ArchiveBox:/data
networks:
  default:
    external:
      name: sakamoto
      
