# Typical laptop setup, with wifi, brightness, battery etc, for
# i3/Sway.

# For X11/i3, you'll want to replace calls to swaymsg with i3-msg, and
# the sway-xkb module with the xkb module.

# fonts we'll be re-using here and there
awesome: &awesome Font Awesome 5 Free:style=solid:pixelsize=14
awesome_brands: &awesome_brands Font Awesome 5 Brands:pixelsize=16

std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}

# This is THE bar configuration
bar:
  height: 26
  location: top
  spacing: 5
  margin: 7

  # Default font
  font: Adobe Helvetica:pixelsize=12

  foreground: ffffffff
  background: 111111cc

  border:
    width: 1
    color: 999999cc
    margin: 5
    top-margin: 0

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13 
              tag: id 
              default: {string: {text: , font: *hack}}
              values:
                1: {string: {text: ﳐ, font: *hack}}  
                2: {string: {text: , font: *hack}}  
                3: {string: {text: , font: *hack}}  
                4: {string: {text: , font: *hack}}  
                5: {string: {text: , font: *hack}}  
                10: {string: {text: "scratchpad", font: *hack}}  
                11: {string: {text: "work", font: *hack}}  

        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            tag: state
            values:
              urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              visible:
                map:
                  tag: occupied
                  values:
                    false: {map: {<<: *river_base}}
                    true: {map: {<<: *river_base, deco: *bg_default}}
              unfocused:
                map:
                  <<: *river_base
              invisible:
                map:
                  tag: occupied
                  values:
                    false: {empty: {}}
                    true: {map: {<<: *river_base, deco: {underline: {size: 3, color: ea6962ff}}}}
    - cpu:
        interval: 2500
        content:
          string: {text: "{cpu1}%"}
    - mem:
        interval: 2500
        content:
          string: {text: "{used:mb}MB"}

  center:
    - mpd:
        host: /run/mpd/socket
        anchors:
          list: &artist_album_title
            spacing: 0
            items:
              - map:
                  tag: state
                  values:
                    playing: {string: {text: "{artist}"}}
                    paused: {string: {text: "{artist}", foreground: ffffff66}}
              - string: {text: " | ", foreground: ffffff66}
              - map:
                  tag: state
                  values:
                    playing: {string: {text: "{album}"}}
                    paused: {string: {text: "{album}", foreground: ffffff66}}
              - string: {text: " | ", foreground: ffffff66}
              - map:
                  tag: state
                  values:
                    playing: {string: {text: "{title}", foreground: ffa0a0ff}}
                    paused: {string: {text: "{title}", foreground: ffffff66}}

        content:
          map:
            margin: 10
            tag: state
            values:
              offline: {string: {text: offline, foreground: ff0000ff}}
              stopped: {string: {text: stopped}}
              paused: {list: *artist_album_title}
              playing: {list: *artist_album_title}

  right:
    - network:
        name: wlan0
        content:
          map:
            tag: carrier
            values:
              false: {empty: {}}
              true:
                map:
                  tag: state
                  default: {string: {text: , font: *awesome, foreground: ffffff66}}
                  values:
                    up:
                      map:
                        tag: ipv4
                        default: {string: {text: , font: *awesome}}
                        values:
                          "": {string: {text: , font: *awesome, foreground: ffffff66}}
    - network:
        name: wlp2s0
        content:
          map:
            tag: state
            default: {string: {text: , font: *awesome, foreground: ffffff66}}
            values:
              down: {string: {text: , font: *awesome, foreground: ff0000ff}}
              up:
                map:
                  tag: ipv4
                  default:
                    - string: {text: , font: *awesome}
                    - string: {text: "{ssid}"}
                  values:
                    "":
                      - string: {text: , font: *awesome, foreground: ffffff66}
                      - string: {text: "{ssid}", foreground: ffffff66}
    - alsa:
        card: hw:PCH
        mixer: Master
        content:
          map:
            tag: online
            values:
              false: {string: {text: , font: *awesome, foreground: ff0000ff}}
              true:
                map:
                  on-click: /bin/sh -c "amixer -q sset Speaker unmute && amixer -q sset Headphone unmute && amixer -q sset Master toggle"
                  tag: muted
                  values:
                    true: {string: {text: , font: *awesome, foreground: ffffff66}}
                    false:
                      ramp:
                        tag: volume
                        items:
                          - string: {text: , font: *awesome}
                          - string: {text: , font: *awesome}
                          - string: {text: , font: *awesome}
                          - string: {text: , font: *awesome}
                          - string: {text: , font: *awesome}
    - backlight:
        name: intel_backlight
        content: [ string: {text: , font: *awesome}, string: {text: "{percent}%"}]
    - battery:
        name: BAT0
        poll-interval: 30
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: ff0000ff, font: *awesome}
                      - string: {text: , foreground: ffa600ff, font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}% {estimate}"}
        content:
          map:
            tag: state
            values:
              unknown:
                <<: *discharging
              discharging:
                <<: *discharging
              charging:
                - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}% {estimate}"}
              full:
                - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}% full"}
              not charging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: ff0000ff, font: *awesome}
                      - string: {text:  , foreground: ffa600ff, font: *awesome}
                      - string: {text:  , foreground: 00ff00ff, font: *awesome}
                      - string: {text:  , foreground: 00ff00ff, font: *awesome}
                      - string: {text:  , foreground: 00ff00ff, font: *awesome}
                      - string: {text:  , foreground: 00ff00ff, font: *awesome}
                      - string: {text:  , foreground: 00ff00ff, font: *awesome}
                      - string: {text:  , foreground: 00ff00ff, font: *awesome}
                      - string: {text:  , foreground: 00ff00ff, font: *awesome}
                      - string: {text:  , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}%"}
    - clock:
        time-format: "%H:%M %Z"
        content:
          - string: {text: , font: *awesome}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: *awesome}
          - string: {text: "{time}"}
    - label:
        content:
          string:
            on-click: loginctl poweroff
            text: 
            font: *awesome
