version: '3.8'
services:
  restserver:
    image: eikek0/sharry:nightly
    container_name: Sharry
    command: /opt/sharry.conf
    ports:
      - "9090:9090"
    volumes:
      - ./sharry.conf:/opt/sharry.conf
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sharrypi
      - POSTGRES_PASSWORD=Hs7s7SABN837NDFg637
      - POSTGRES_DB=db_sharry
    restart: always
volumes:
  postgres_data:
networks:
  default:
    external:
      name: pacman

